WebsiteThuongMaiDienTu/WEB/WEB/WEB/ThuongMaiDienTu/ThuongMaiDienTu/Controllers/TaiKhoanCaNhanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using ThuongMaiDienTu.Models;

namespace ThuongMaiDienTu.Controllers
{
    public class TaiKhoanCaNhanController : Controller
    {
        ThuongMaiDienTuEntities db = new ThuongMaiDienTuEntities();
        
        // GET: TaiKhoanCaNhan
        public ActionResult TrangCaNhan()
        {
            return View();
        }
        [HttpGet]
        public ActionResult ThongTinCaNhan()
        {
            TaiKhoan TK = Session["TaiKhoan"] as TaiKhoan;
            try
            {
                return View(db.NguoiDungs.Include("TaiKhoans").Single(t => t.ID == TK.ID));
            }
            catch
            {
                return RedirectToAction("TrangChu", "Home");
            }
        }
        public ActionResult SoDiaChi()
        {
            TaiKhoan TK = Session["TaiKhoan"] as TaiKhoan;
            if (TK != null)
            {
                List<ThongTinLienHe> TTs = db.ThongTinLienHes.Include("Xa_Phuong").Where(t => t.ID == TK.ID).ToList();
                return View(TTs);
            }
            else
                return RedirectToAction("TrangChu", "Home");
        }
        public ActionResult ThemDiaChiMoi()
        {
            ViewBag.loi = -1;
            ViewBag.Tinh = db.Tinh_ThanhPho.ToList();
            ViewBag.Quan = db.Quan_Huyen.ToList();
            ViewBag.Xa = db.Xa_Phuong.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult ThemDiaChiMoi(FormCollection f, string url)
        {
            
            TaiKhoan TK = Session["TaiKhoan"] as TaiKhoan;
            if (TK != null)
            {
                if (ModelState.IsValid)
                {
                    string HoVaTen = f["HoVaTen"];
                    string SoDienThoai = f["SoDienThoai"];
                    string MaXP = f["XaPhuong"];
                    ViewBag.Tinh = db.Tinh_ThanhPho.ToList();
                    ViewBag.Quan = db.Quan_Huyen.ToList();
                    ViewBag.Xa = db.Xa_Phuong.ToList();
                    if (HoVaTen == null || SoDienThoai == null || MaXP == null)
                        return View();
                    string LoaiDiaChi = f["LoaiDiaChi"];
                    bool MacDinh = (f["MacDinh"] == null) ? false : true;
                    ThongTinLienHe lh = new ThongTinLienHe();

                    lh.NguoiDung = db.NguoiDungs.Single(nd => nd.ID == TK.ID);
                    lh.ID = TK.ID;
                    lh.LoaiDiaChi = LoaiDiaChi;
                    lh.MacDinh = MacDinh;
                    lh.MaXP = MaXP;
                    lh.DiaChiCuThe = f["DiaChiCuThe"];
                    lh.SoDienThoai = SoDienThoai;
                    lh.TenNguoiNhan = HoVaTen;
                    lh.MaLH = lh.ID.ToString().Trim() + "LH" + db.ThongTinLienHes.Count(t => t.ID == lh.ID).ToString();
                    lh.An = false;

                    db.ThongTinLienHes.Add(lh);
                    db.SaveChanges();
                    ViewBag.checkDC = true;
                }
                return Redirect(url);
            }
            else
                return RedirectToAction("TrangChu", "Home");
        }
        [HttpGet]
        public ActionResult XoaDiaChi(string MaLH)
        {
            ThongTinLienHe tt = db.ThongTinLienHes.Single(t => t.MaLH.Equals(MaLH));
            tt.An = true;
            db.ThongTinLienHes.Attach(tt);
            db.Entry(tt).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("SoDiaChi");
        }
        public ActionResult SuaDiaChi(string MaLH, string url)
        {
            TaiKhoan TK = Session["TaiKhoan"] as TaiKhoan;
            if (TK != null)
            {
                ViewBag.Tinh = db.Tinh_ThanhPho.ToList();
                ViewBag.Quan = db.Quan_Huyen.ToList();
                ViewBag.Xa = db.Xa_Phuong.ToList();
                Session["url"] = url;
                return View(db.ThongTinLienHes.Single(t => t.MaLH.Equals(MaLH)));
            } 
            else
                return RedirectToAction("TrangChu", "Home");
        }
        [HttpPost]
        public ActionResult SuaDiaChi(FormCollection f)
        {
            TaiKhoan TK = Session["TaiKhoan"] as TaiKhoan;
            if (TK != null)
            {
                string malh = f["MaLH"];
                ThongTinLienHe ttlh = db.ThongTinLienHes.Single(t => t.MaLH.Equals(malh));
                ttlh.MaXP = f["XaPhuong"];
                ttlh.TenNguoiNhan = f["HoVaTen"];
                ttlh.SoDienThoai = f["SoDienThoai"];
                ttlh.MacDinh = (f["MacDinh"] == null) ? false : true;
                ttlh.LoaiDiaChi = f["LoaiDiaChi"];
                db.ThongTinLienHes.Attach(ttlh);
                db.Entry(ttlh).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return Redirect(Session["url"].ToString());
            } 
            else
                return RedirectToAction("TrangChu", "Home");
        }
        [HttpGet]
        public ActionResult DatlamMacDinh(string MaLH)
        {
            
            ThongTinLienHe tt = db.ThongTinLienHes.Single(t => t.MaLH.Equals(MaLH));
            tt.MacDinh = true;
            db.ThongTinLienHes.Attach(tt);
            db.Entry(tt).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("SoDiaChi");
        }
        public ActionResult ThanhToan()
        {
            return View();
        }
        public ActionResult DoiMatKhau()
        {
            TaiKhoan TK = Session["TaiKhoan"] as TaiKhoan;
            if (TK != null)
            {
                return View();
            }
            else
                return RedirectToAction("TrangChu", "Home");
        }
        public ActionResult HuyDonHang(string MaDH, string url)
        {
            TaiKhoan tk = Session["TaiKhoan"] as TaiKhoan;
            if (tk != null)
            {
                DonHang DH = db.DonHangs.Single(d => d.MaDonHang.Equals(MaDH));
                DH.TrangThai = "Đã hủy";
                db.Entry(DH).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return Redirect(url);
            }
            return RedirectToAction("TrangChu", "Home");
        }
        [HttpPost]
        public ActionResult DoiMatKhau(FormCollection f)
        {
            TaiKhoan TK = Session["TaiKhoan"] as TaiKhoan;
            if (TK.MatKhau.Equals(HoTro.HashToSHA512(f["MKHienTai"])))
            {
                string MK = HoTro.HashToSHA512(f["MKMoi"].ToString());
                db.ThayDoiMatKhau(TK.ID, MK);
                db.SaveChanges();
                return RedirectToAction("ThongTinCaNhan");
            }
            ViewData["MKHienTai"] = "Sai mật khẩu, vui lòng nhập lại!";
            return View();
        }
        public ActionResult XemChiTietDonHang(string maDH)
        {
            TaiKhoan TK = Session["TaiKhoan"] as TaiKhoan;
            if (TK != null)
            {
                DonHang Dh = null;
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("https://localhost:44304/api/");
                    var responseTask = client.GetAsync("DonHangApi/XemChiTietDonHang?maDH=" + maDH);
                    responseTask.Wait();
                    var result = responseTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readSP = result.Content.ReadAsAsync<DonHang>();
                        readSP.Wait();
                        Dh = readSP.Result;
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Erorr occured !!!");
                    }
                    return View(Dh);
                }
            }
            else
                return RedirectToAction("TrangChu", "Home");
            
        }
        public ActionResult YeuThich()
        {
            return View();
        }
        public ActionResult UuDaiCuaToi()
        {
            return View();
        }
        public ActionResult DoiTra()
        {
            return View();
        }
        public ActionResult QuanLyDonHang()
        {
            TaiKhoan TK = Session["TaiKhoan"] as TaiKhoan;
            if (TK != null)
            {
                List<DonHang> GHangs = db.DonHangs.Include("ThongTinLienHe").Where(gh => gh.ThongTinLienHe.ID == TK.ID).ToList();
                return View(GHangs);
            }
            else
                return RedirectToAction("TrangChu", "Home");
        }
        [HttpPost]
        public ActionResult ThongTinCaNhan(FormCollection f)
        {
            TaiKhoan TK = Session["TaiKhoan"] as TaiKhoan;
            if (TK != null)
            {
                NguoiDung ND = db.NguoiDungs.Include("TaiKhoans").FirstOrDefault(t => t.ID == TK.ID);
                bool check = true;
                if (f["Email"] == "" || f["Email"] == null)
                {
                    ViewData["Email"] = "Email không được để trống";
                    check = false;
                }
                else
                {
                    if (!HoTro.IsEmail(f["Email"]))
                    {
                        ViewData["Email"] = "Email không đúng định dạng, hãy nhập lại";
                        check = false;
                    }
                    else
                        ND.Email = f["Email"];
                }
                ND.AnhDaiDien = f["AnhMoi"];
                if (string.IsNullOrEmpty(f["HoVaTen"]) || f["HoVaTen"] == null)
                {
                    ViewData["HoVaTen"] = "Họ tên của bạn không được để trống";
                    check = false;

WebsiteThuongMaiDienTu/WEB/WEB/WEB/ThuongMaiDienTu/ThuongMaiDienTu/Views/TaiKhoanCaNhan/DoiTra.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DoiTra</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

WebsiteThuongMaiDienTu/WEB/WEB/WEB/ThuongMaiDienTu/ThuongMaiDienTu/Views/TaiKhoanCaNhan/SoDiaChi.cshtml
@using ThuongMaiDienTu.Models
@model IEnumerable<ThuongMaiDienTu.Models.ThongTinLienHe>
@{
    ViewBag.Title = "Sổ địa chỉ của bạn";
    Layout = "~/Views/TaiKhoanCaNhan/TrangCaNhan.cshtml";
}
<link href="~/Content/SoDiaChi.css" rel="stylesheet" />

<div id="list-item-2" style="min-height:900px;">
    <h4>
        <i class="bi bi-house-gear-fill"></i>
        Sổ địa chỉ
    </h4>
    <hr />
    <div>
        <div class="row">
            <div class="row">
                <button class="btn w-100 btn-info  itemm btn_dc" data-bs-toggle="modal" data-bs-target="#ThemDiaChi" style="margin-left:10px; height:70px; font-size:20px;">
                    <svg style="margin-bottom:4px;" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus-square-dotted" viewBox="0 0 16 16">
                        <path d="M2.5 0c-.166 0-.33.016-.487.048l.194.98A1.51 1.51 0 0 1 2.5 1h.458V0H2.5zm2.292 0h-.917v1h.917V0zm1.833 0h-.917v1h.917V0zm1.833 0h-.916v1h.916V0zm1.834 0h-.917v1h.917V0zm1.833 0h-.917v1h.917V0zM13.5 0h-.458v1h.458c.1 0 .199.01.293.029l.194-.981A2.51 2.51 0 0 0 13.5 0zm2.079 1.11a2.511 2.511 0 0 0-.69-.689l-.556.831c.164.11.305.251.415.415l.83-.556zM1.11.421a2.511 2.511 0 0 0-.689.69l.831.556c.11-.164.251-.305.415-.415L1.11.422zM16 2.5c0-.166-.016-.33-.048-.487l-.98.194c.018.094.028.192.028.293v.458h1V2.5zM.048 2.013A2.51 2.51 0 0 0 0 2.5v.458h1V2.5c0-.1.01-.199.029-.293l-.981-.194zM0 3.875v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zM0 5.708v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zM0 7.542v.916h1v-.916H0zm15 .916h1v-.916h-1v.916zM0 9.375v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zm-16 .916v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zm-16 .917v.458c0 .166.016.33.048.487l.98-.194A1.51 1.51 0 0 1 1 13.5v-.458H0zm16 .458v-.458h-1v.458c0 .1-.01.199-.029.293l.981.194c.032-.158.048-.32.048-.487zM.421 14.89c.183.272.417.506.69.689l.556-.831a1.51 1.51 0 0 1-.415-.415l-.83.556zm14.469.689c.272-.183.506-.417.689-.69l-.831-.556c-.11.164-.251.305-.415.415l.556.83zm-12.877.373c.158.032.32.048.487.048h.458v-1H2.5c-.1 0-.199-.01-.293-.029l-.194.981zM13.5 16c.166 0 .33-.016.487-.048l-.194-.98A1.51 1.51 0 0 1 13.5 15h-.458v1h.458zm-9.625 0h.917v-1h-.917v1zm1.833 0h.917v-1h-.917v1zm1.834-1v1h.916v-1h-.916zm1.833 1h.917v-1h-.917v1zm1.833 0h.917v-1h-.917v1zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z" />
                    </svg>
                    THÊM ĐỊA CHỈ MỚI
                </button>
                <div class="modal fade" id="ThemDiaChi" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg ">
                        <div class="modal-content" style="margin-top:100px;">
                            <div class="modal-header">
                                <h4 class="modal-title" id="staticBackdropLabel">Thêm địa chỉ mới</h4>
                            </div>
                            @Html.Action("ThemDiaChiMoi");
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin-top: 20px;">
                @{ var sl = 0;
                    foreach (var item in Model)
                    {
                        if (item.An == false)
                        {
                            sl++;
                                <div class="itemm row" style=" margin-left: 10px; margin-bottom:20px; padding:15px;position:relative;">
                                    <div class="col-lg-9 col-12">
                                        <b style="font-size:17px; margin-bottom:15px;">@item.TenNguoiNhan</b><br />
                                        <a><span class="mo">Địa chỉ: </span> @HoTro.LayDiaChi(item.MaXP) </a><br />
                                        <a><span class="mo">Địa điểm cụ thể: </span>@item.DiaChiCuThe</a><br />
                                        <a><span class="mo">Số điện thoại: </span>@item.SoDienThoai </a>
                                    </div>
                                    <div class="col-lg-3 col-12">
                                        <div class="row">
                                            <div class="col-5">
                                                <div class="row">
                                                    <div class="col-lg-12 col-6" style="margin-top:5px;">
                                                        <center><a href="@Url.Action("SuaDiaChi", "TaiKhoanCaNhan", new { MaLH = item.MaLH, url = Request.Url.ToString() })" class="btn w-100 btn-outline-info">Sửa</a></center>
                                                    </div>
                                                    <div class="col-lg-12 col-6" style="margin-top:5px;">
                                                        <center><a href="@Url.Action("XoaDiaChi", "TaiKhoanCaNhan", new { MaLH = item.MaLH })" class="btn w-100 btn-outline-danger">Xóa</a></center>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-7" style="position:relative;">
                                                <a href="@Url.Action("DatlamMacDinh", "TaiKhoanCaNhan", new { MaLH = item.MaLH })" style="position:absolute; bottom:0; right:0;" class="btn btn-outline-primary">Đặt làm mặt định</a>
                                            </div>
                                        </div>
                                    </div>
                                    @if (item.MacDinh == true)
                                    {
                                    <div class="macdinh">
                                        Mặc định
                                    </div>
                                    }
                                </div>
                        }
                    }
                    if(sl==0)
            {
            <center><h5>Bạn chưa cập nhật địa chỉ giao hàng</h5></center>
            }
                }
            </div>
        </div>
    </div>
</div>

WebsiteThuongMaiDienTu/WEB/WEB/WEB/ThuongMaiDienTu/ThuongMaiDienTu/Views/TaiKhoanCaNhan/ThanhToan.cshtml
<style>
    .btn_dc {
        border: 1px dashed #0dcaf0;
    }

        .btn_dc:hover {
            border: 1px dashed white;
            color: white;
        }

    .mo {
        color: #777777;
    }
</style>
<div class="row">
    <div class="row">
        <button class="btn w-100 btn-info  itemm btn_dc" style="margin-left:10px; height:70px; font-size:20px;">
            <svg style="margin-bottom:4px;" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-plus-square-dotted" viewBox="0 0 16 16">
                <path d="M2.5 0c-.166 0-.33.016-.487.048l.194.98A1.51 1.51 0 0 1 2.5 1h.458V0H2.5zm2.292 0h-.917v1h.917V0zm1.833 0h-.917v1h.917V0zm1.833 0h-.916v1h.916V0zm1.834 0h-.917v1h.917V0zm1.833 0h-.917v1h.917V0zM13.5 0h-.458v1h.458c.1 0 .199.01.293.029l.194-.981A2.51 2.51 0 0 0 13.5 0zm2.079 1.11a2.511 2.511 0 0 0-.69-.689l-.556.831c.164.11.305.251.415.415l.83-.556zM1.11.421a2.511 2.511 0 0 0-.689.69l.831.556c.11-.164.251-.305.415-.415L1.11.422zM16 2.5c0-.166-.016-.33-.048-.487l-.98.194c.018.094.028.192.028.293v.458h1V2.5zM.048 2.013A2.51 2.51 0 0 0 0 2.5v.458h1V2.5c0-.1.01-.199.029-.293l-.981-.194zM0 3.875v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zM0 5.708v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zM0 7.542v.916h1v-.916H0zm15 .916h1v-.916h-1v.916zM0 9.375v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zm-16 .916v.917h1v-.917H0zm16 .917v-.917h-1v.917h1zm-16 .917v.458c0 .166.016.33.048.487l.98-.194A1.51 1.51 0 0 1 1 13.5v-.458H0zm16 .458v-.458h-1v.458c0 .1-.01.199-.029.293l.981.194c.032-.158.048-.32.048-.487zM.421 14.89c.183.272.417.506.69.689l.556-.831a1.51 1.51 0 0 1-.415-.415l-.83.556zm14.469.689c.272-.183.506-.417.689-.69l-.831-.556c-.11.164-.251.305-.415.415l.556.83zm-12.877.373c.158.032.32.048.487.048h.458v-1H2.5c-.1 0-.199-.01-.293-.029l-.194.981zM13.5 16c.166 0 .33-.016.487-.048l-.194-.98A1.51 1.51 0 0 1 13.5 15h-.458v1h.458zm-9.625 0h.917v-1h-.917v1zm1.833 0h.917v-1h-.917v1zm1.834-1v1h.916v-1h-.916zm1.833 1h.917v-1h-.917v1zm1.833 0h.917v-1h-.917v1zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z" />
            </svg>
            THÊM TÀI KHOẢN NGÂN HÀNG
        </button>
    </div>
    <div class="row" style="margin-top: 20px;">
        <div class="itemm row" style=" margin-left: 10px; padding:15px;">
            <div class="col-md-9 col-sm-12">
                <b style="font-size:17px; margin-bottom:15px;"> Lê Phát Đạt</b><br />
                <a><span class="mo">Tên chủ tài khoản: </span> Le Phat Dat</a><br />
                <a><span class="mo">Ngân hàng: </span> Sacombank</a><br />
                <a><span class="mo">Số tài khoản </span> 1016886883</a>
            </div>
            <div class="col-md-3 col-sm-12">
                <div class="row" style="padding:25px;">
                        <center><button class="btn btn-outline-danger">Xóa tài khoản</button></center>
                </div>
            </div>
        </div>
    </div>
</div>

WebsiteThuongMaiDienTu/WEB/WEB/WEB/ThuongMaiDienTu/ThuongMaiDienTu/Views/TaiKhoanCaNhan/ThemDiaChiMoi.cshtml
@using ThuongMaiDienTu.Models
@{
    List<Tinh_ThanhPho> Tinhs = ViewBag.Tinh as List<Tinh_ThanhPho>;
    List<Quan_Huyen> Quans = ViewBag.Quan as List<Quan_Huyen>;
    List<Xa_Phuong> Xas = ViewBag.Xa as List<Xa_Phuong>;
}
<style>
    textarea {
        padding: 10px 20px;
    }

    .loidl {
        color: red;
        position: absolute;
        margin-left: 2px;
        font-size: 13px;
    }

    .ViewLoi {
        position: relative;
    }

    .bomtom {
        margin-bottom: 40px;
    }
</style>

@if (ViewBag.checkDC != null)
{
    if (ViewBag.checkDC == true)
    {
        ViewBag.checkDC = null;
        <script>
            setTimeout(function () {
            alert("Cập nhật thông tin thành công");
        }, 300);
        </script>
    }
    else
    {
        ViewBag.checkDC = null;
        <script>
            setTimeout(function () {
                alert("Đã xảy ra lỗi! vui lòng thử lại sau");
            }, 300);
        </script>
    }
}
@using (Html.BeginForm("ThemDiaChiMoi","TaiKhoanCaNhan",new {url = Request.Url.ToString() },method:FormMethod.Post))
{
    <div class="modal-body" style="height:600px; padding:50px;">
        <div class="row">
            <div class="row">
                <div class="col-6 bomtom">
                    <input type="text" id="HoVaTen" name="HoVaTen" class="btn w-100 tt_lh" placeholder="Họ và tên" title="Nhập học và tên người nhận" />
                    <div class="ViewLoi">
                        <span class="loidl"></span>
                    </div>
                </div>

                <div class="col-6 bomtom">
                    <input type="text" id="SoDienThoai" class="btn w-100 tt_lh" oninput="CheckPhone(this)" name="SoDienThoai" maxlength="10" placeholder="Số điện thoại" title="Nhập số điện thoại người nhận" />
                    <div class="ViewLoi">
                        <span class="loidl"></span>
                    </div>
                </div>
            </div>
            <div class="row bomtom">
                <div class="col-4">
                    <select name="TinhTP" onchange="CapNhatQuan(this)" id="ChonTinh" class="form-select" aria-label="Default select example">
                        <option selected>Chọn Tỉnh/Thành Phố</option>
                        @foreach (var item in Tinhs)
                        {
                            <option value="@item.MaTinh">@item.TenTinh</option>
                        }
                    </select>
                </div>
                <div class="col-4">
                    <select name="QuanHuyen" id="ChonQuan" disabled onchange="CapNhatXa(this)" class="form-select" aria-label="Default select example">
                        <option selected>Chọn Quận/Huyện</option>
                        @foreach (var item in Quans)
                        {
                            <option class="@("Tinh"+item.MaTinh)" style="display:none" value="@item.MaQH">@item.TenHuyen</option>
                        }
                    </select>
                </div>
                <div class="col-4">
                    <select name="XaPhuong" id="ChonXa" onchange="HienDiaChiCuThe(this)" disabled class="form-select" aria-label="Default select example">
                        <option selected>Chọn Xã/Phường</option>
                        @foreach (var item in Xas)
                        {
                            <option class="@("Quan"+item.MaQH)" style="display:none" value="@item.MaXP">@item.TenXa</option>
                        }
                    </select>
                </div>
                <div class=" col-12 ViewLoi">
                    <span class="loidl"></span>
                </div>
            </div>
            <div class="row" style="padding:25px;">
                <textarea maxlength="100" name="DiaChiCuThe" id="diachicuthe" disabled placeholder="Địa chỉ cụ thể" title="Nhập địa chỉ của thể" class="w-100" style="min-height:100px; max-height:200px; margin-top:-10px;"></textarea>
                <div class="ViewLoi" style="margin-left:-12px;">
                    <span class="loidl"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <span>Loại địa chỉ</span>
                    <br />
                    <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                        <input type="radio" class="btn-check" name="LoaiDiaChi" value="Nhà riêng" id="Loai1" autocomplete="off" checked>
                        <label class="btn btn-outline-info" for="Loai1">Nhà riêng</label>
                        <input type="radio" class="btn-check" name="LoaiDiaChi" value="Văn phòng" id="Loai2" autocomplete="off">
                        <label class="btn btn-outline-info" for="Loai2">Văn phòng</label>
                    </div>
                </div>
                <div class=" col-12">
                    <div class="form-check form-switch" style="padding-top:25px;">
                        <input class="form-check-input" type="checkbox" value="1" name="MacDinh" role="switch" id="flexSwitchCheckDefault">
                        <label class="form-check-label" for="flexSwitchCheckDefault">Đặt làm mặt định</label>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <div>
            <input type="button" value="Hủy Lưu" id="HuyLuuDiaChi" class="btn btn-outline-danger" data-bs-dismiss="modal">
        </div>
        <div>
            <a value="Lưu" id="KT" class="btn btn-outline-info">Lưu</a>
            <button id="ThemDiaChiMoi" type="submit" hidden data-bs-dismiss="modal">lllll</button>
        </div>
    </div>
}

<script src="~/js/Checkfromm.js"></script>
<script src="~/js/ThemDiaChiMoii.js"></script>